# Generated by Django 4.2.7 on 2023-11-16 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='vehicle_images')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('year_of_prod', models.IntegerField()),
                ('mileage', models.CharField(max_length=15)),
                ('hometown', models.CharField(max_length=30)),
                ('currently_in', models.CharField(max_length=30)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
