# Generated by Django 4.2.7 on 2023-11-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andrei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andrei.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='andrei.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
