# Generated by Django 4.2.7 on 2023-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andrei', '0002_additionalimage_mainimage_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='_type',
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='image',
            field=models.ImageField(upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to='vehicle_images/'),
        ),
    ]
