# Generated by Django 4.2.7 on 2024-01-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andrei', '0004_vehicle_transmission_alter_additionalimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='_type',
            new_name='vtype',
        ),
    ]
